config/routes.rb
Rails.application.routes.draw do
  get 'products/report'
  get 'search/create'
  get 'search/report'
  resources :orders
  devise_for :users, :skip => [:registrations]
  as :user do
  # Registrations
  get   '/users/sign_up'   => 'users/registrations#new', as: :new_user_registration
  post  '/users/sign_up'   => 'users/registrations#create', as: :user_registration
end
  resources :products
  resources :invoices
  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
require 'csv'

class Product < ApplicationRecord
  has_many :order
  validates :nombre, presence: true;
  validates :descripcion, presence: true;
  validates :marca, presence: true;
  validates :categoria, presence: true;
  validates :cantidad, presence: true;
  validates :precio, presence: true;

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def report

    @date_start = "#{params[:date_start]}"
    @date_end = "#{params[:date_end]}"

    #@products = Product.where("nombre LIKE ? OR descripcion LIKE ? OR marca LIKE ? OR categoria LIKE ?", palabra, palabra, palabra, palabra)
    if @date_start and @date_end
      @products = Product.where("created_at BETWEEN ? AND ?",@date_start, @date_end)
    else
      @products = Product.all
    end

    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'products/informe', pdf: "Informe"  }
      format.csv {render text: @product.to_csv }
      format.xls #{send_data @products.to_csv(col_sep: "\t")}
    end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nombre, :descripcion, :marca, :categoria, :cantidad, :precio)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <%= form_with(model: product, local: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field col s10">
      <%= form.label :nombre %>
      <%= form.text_field :nombre, id: :product_nombre %>
    </div>

    <div class="field col s10">
      <%= form.label :descripcion %>
      <%= form.text_area :descripcion, id: :product_descripcion, class:"materialize-textarea" %>
    </div>

    <div class="field col s10">
      <%= form.label :marca %>
      <%= form.text_field :marca, id: :product_marca %>
    </div>

    <div class="field col s10">
      <%= form.label :categoria %>
      <%= form.text_field :categoria, id: :product_categoria %>
    </div>

    <div class="field col s10">
      <%= form.label :cantidad %>
      <%= form.number_field :cantidad, id: :product_cantidad %>
    </div>

    <div class="field col s10">
      <%= form.label :precio %>
      <%= form.number_field :precio, id: :product_precio %>
    </div>

    <div class="actions col s10">
      <%= form.submit @tipo,class:"waves-effect waves-light btn"%>
    </div>
  <% end %>

app/views/products/_product.html.erb
<h1>Productos</h1>
  <table class="responsive-table striped centered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Marca</th>
        <th>Categoria</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= product.nombre %></td>
          <td><%= product.descripcion %></td>
          <td><%= product.marca %></td>
          <td><%= product.categoria %></td>
          <td><%= product.cantidad %></td>
          <td><%= product.precio %></td>
        </tr>
    </tbody>
  </table>

app/views/products/edit.html.erb
<div class="card-panel grey lighten-5">
   <div class="container">
     <div class="row">
        <%@tipo = "Editar producto" %>
       <h1>Editar Producto</h1>
       <%= render 'form', product: @product %>
       <div class="actions col s10">
         <%= link_to 'Regresar', products_path, class: "black-text text-darken-2" %>
       </div>
     </div>
   </div>
</div>

app/views/products/index.html.erb
<div class="card-panel grey lighten-5">
  <p id="notice"><%= notice %></p>

  <h1>Productos</h1>

  <%= link_to "Informe", "/products/report", class:"posicion btn btn-outline-success"%>
  <% if current_user.try(:admin?) %>
  <table class="responsive-table striped centered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Marca</th>
        <th>Categoria</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.nombre %></td>
          <td><%= product.descripcion %></td>
          <td><%= product.marca %></td>
          <td><%= product.categoria %></td>
          <td><%= product.cantidad %></td>
          <td><%= product.precio %></td>
          <td><%= link_to 'Editar', edit_product_path(product), class:"teal-text text-darken-2" %></td>
          <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"red-text text-darken-2" %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <table class="responsive-table striped centered">
      <thead>
        <tr>
          <th>#</th>
          <th>Nombre</th>
          <th>Cantidad</th>
          <th>Precio</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each_with_index do |product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= product.nombre %></td>
            <td><%= product.cantidad %></td>
            <td><%= product.precio %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <br>
  <% if current_user.try(:admin?) %>
      <%= link_to 'Nuevo Producto', new_product_path, class:"waves-effect waves-light btn" %>
  <% end %>
</div>

app/views/products/informe.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
    <!-- GOOGLE FONTS tipo de letra -->
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col">
          <%= wicked_pdf_image_tag 'logo.png'%><br><br>
      </div>
      <div class="col-8">
        <h3 class="letra_titulo">Tienda online</h3>
      </div>
    </div>
    <div class="container">
      <h5 class="letra_cuerpo">El siguiente informe presenta los producto agregados a la tienda desde <%= @date_start %> hasta <%= @date_end%></h5>
      <h3 class="letra_cuerpo">Productos</h3><br>
      <% if current_user.try(:admin?) %>
        <table class="table table-striped letra_cuerpo centered">
          <thead>
            <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Marca</th>
              <th>Fecha de creacion</th>
              <th>Cantidad</th>
              <th>Precio</th>
            </tr>
          </thead>

          <tbody>
            <% @products.each_with_index do |product, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= product.nombre %></td>
                <td><%= product.marca %></td>
                <td><%= product.created_at.strftime("%Y-%m-%d")%></td>
                <td><%= product.cantidad %></td>
                <td><%= product.precio %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <table class="table table-striped letra_cuerpo centered">
          <thead>
            <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Cantidad</th>
              <th>Precio</th>
            </tr>
          </thead>

          <tbody>
            <% @products.each_with_index do |product, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= product.nombre %></td>
                <td><%= product.cantidad %></td>
                <td><%= product.precio %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>



    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/new.html.erb
 <div class="card-panel grey lighten-5">
    <div class="container">
      <div class="row">
        <h1>Nuevo Producto</h1>
        <%@tipo = "Crear producto" %>
        <%= render 'form', product: @product %>

         <div class="actions col s10">
           <%= link_to 'Regresar', products_path, class: "black-text text-darken-2" %>
        </div>
     </div>
  </div>
</div>

app/views/products/report.html.erb
<div class="card-panel grey lighten-5">
<div class="container-fluid"><br>
  <h3>Informe de productos</h3>
  <div class="row">
    <div class="col s6">
      <%= form_tag "/products/report", method: :get do %>
        <%= label :date_start, "Fecha de inicio"%>
        <%= date_field_tag :date_start, nil %>
        <%= label :date_end, "Fecha final"%>
        <%= date_field_tag :date_end, nil %>
        <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "Imprimir PDF" ,products_report_url(:format => :pdf, params: request.query_parameters), class: "btn btn-danger posicion_pdf"%>
<%= link_to "Imprimir Excel" ,products_report_url(:format => :xls, params: request.query_parameters), class: "btn btn-danger posicion_xls"%>



  <p id="notice"><%= notice %></p>

  <h1>Productos</h1>
  <% if current_user.try(:admin?) %>
    <table class="taresponsive-table striped centered">
      <thead>
        <tr>
          <th>#</th>
          <th>Nombre</th>
          <th>Marca</th>
          <th>Categoria</th>
          <th>Cantidad</th>
          <th>Precio</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each_with_index do |product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= product.nombre %></td>
            <td><%= product.marca %></td>
            <td><%= product.categoria%></td>
            <td><%= product.cantidad %></td>
            <td><%= product.precio %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <table class="responsive-table striped centered">
      <thead>
        <tr>
          <th>#</th>
          <th>Nombre</th>
          <th>Cantidad</th>
          <th>Precio</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each_with_index do |product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= product.nombre %></td>
            <td><%= product.cantidad %></td>
            <td><%= product.precio %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  </div>


  <br>
</div>

app/views/products/report.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <% if current_user.try(:admin?) %>
      <Table>
        <Row>
          <Cell><Data ss:Type="String">Nombre</Data></Cell>
          <Cell><Data ss:Type="String">Descripcion</Data></Cell>
          <Cell><Data ss:Type="String">Marca</Data></Cell>
          <Cell><Data ss:Type="String">Categoria</Data></Cell>
          <Cell><Data ss:Type="String">Fecha creacion</Data></Cell>
          <Cell><Data ss:Type="String">Cantidad</Data></Cell>
          <Cell><Data ss:Type="String">Precio</Data></Cell>
        </Row>
        <% @products.each do |product| %>
          <Row>
            <Cell><Data ss:Type="String"><%= product.nombre %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.descripcion %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.marca %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.categoria %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.created_at.strftime("%Y-%m-%d") %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.cantidad %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.precio %></Data></Cell>
          </Row>
        <% end %>
      </Table>
    <% else %>
      <Table>
        <Row>
          <Cell><Data ss:Type="String">Nombre</Data></Cell>
          <Cell><Data ss:Type="String">Cantidad</Data></Cell>
          <Cell><Data ss:Type="String">Precio</Data></Cell>
        </Row>
        <% @products.each do |product| %>
          <Row>
            <Cell><Data ss:Type="String"><%= product.nombre %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.cantidad %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.precio %></Data></Cell>
          </Row>
        <% end %>
      </Table>
    <% end %>


  </Worksheet>
</Workbook>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @product.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @product.descripcion %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @product.marca %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @product.categoria %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @product.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.precio %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Regresar', products_path %>